[FIX] scsi: ufs: Release clock if DMA map fails [Fix commit 992203a7c0d5 "scsi: ufs: Release clock if DMA map fails"]
../drivers/scsi/ufs/ufshcd.c:2688:3: error: too few arguments to function 'ufshcd_release'
../drivers/scsi/ufs/ufshcd.c:1406:6: note: declared here

change it to false better than we revert it.
[Reference: chips-project/msm-4.14@c9b485c]

Change-Id: Ic1927c41823ba770ef2a709402286b01119311ae
Signed-off-by: fadlyas07 <fadlyardhians@gmail.com>
Signed-off-by: entaromia <30384045+entaromia@users.noreply.github.com>